### ISSUE TITLE
SNES.png overlay is missing

### ISSUE THREAD

**Issue by usersaurus** [dragoonDorise/pegasus-android-metadata#12]
https://github.com/dragoonDorise/pegasus-android-metadata/blob/b24045cf0310f745e99de83c01366b6104c9847e/internal/rg552/RetroArch/overlays/pegasus/SNES.cfg#L3

**Comment by dragoonDorise** [comment]
Hi, Im closing this, the file you are referring to is an old file, now all systems use the same overlays, the changes between handhelds are on the scale configurations. I'll delete these files on a next version.
